wandb_version: 1

seed:
  desc: null
  value: 32678456782
device:
  desc: null
  value: cuda
num_workers:
  desc: null
  value: 4
data_root:
  desc: null
  value: /network/scratch/y/yuyan.chen/anuraset/
metadata:
  desc: null
  value: INCT20955_metadata.csv
num_classes:
  desc: null
  value: 12
folder_name:
  desc: null
  value: resnet18_INCT20955
image_size:
  desc: null
  value:
  - 224
  - 448
num_epochs:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.01
weight_decay:
  desc: null
  value: 0.001
model_type:
  desc: null
  value: resnet18
pretrained:
  desc: null
  value: true
multilabel:
  desc: null
  value: true
wandb_project:
  desc: null
  value: anuraset
wandb_entity:
  desc: null
  value: mila-org-test
wandb_name:
  desc: null
  value: resnet18_INCT20955_baseline
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1720927604
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.8
      5: 0.17.1
      8:
      - 2
      - 5
      13: linux-x86_64
